name: 'Setup Protoc and Generate'
description: 'Installs Golang, protoc, Go plugins and generates proto files'
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
        cache: true

    - name: Install protoc
      uses: arduino/setup-protoc@v3.0.0

    - name: Instal proto plugins
      shell: bash
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
        go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
   
    - name: Generate proto
      shell: bash
      run: |
        protoc -I $PROTO_PATH -I $INCLUDE_PATH \
        --go_out=$PROTO_PATH --go_opt=paths=source_relative \
        --go-grpc_out=$PROTO_PATH --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=$PROTO_PATH --grpc-gateway_opt=paths=source_relative \
        --openapiv2_out=$PROTO_PATH --openapiv2_opt=allow_merge=true,merge_file_name=kartg \
        $PROTO_PATH/service.proto


    - name: Install dependencies
      shell: bash
      run: |
        go mod tidy
